#------------------------------------------------------------------------------
#
# Copyright Inixe S.A
#
# File: ci.yml
# Purpose: Github Actions CI pipeilne
#------------------------------------------------------------------------------
on:
  push:
    branches:
      - master
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    name: Publish Nuget
    steps:
    - name: Get Source
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Set Version
      shell: pwsh
      run: |
        $Version=$Env:GITHUB_REF -replace "refs/tags/v", ""
        $IsPublishVersion = "TRUE"
        If ($Version -eq 'refs/heads/master') {
          $IsPublishVersion = "FALSE"
          $Version="1.0.0-preview"
        } 
        Add-Content $Env:GITHUB_ENV "PUBLISH_PACKAGE=$($IsPublishVersion)"
        Add-Content $Env:GITHUB_ENV "VERSION=$($Version)"
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      shell: pwsh
      run: |
        dotnet build -c Release -p:Version=${{ env.VERSION }}
    - name: Test
      run: |
        dotnet test --no-build -c Release --verbosity normal
    - name: Pack
      shell: pwsh
      run: |
        dotnet pack src\Inixe.Extensions.AwsConfigSource\Inixe.Extensions.AwsConfigSource.csproj -c Release -p:NuspecBasePath=. -p:Version=${{ env.VERSION }}
    - name: Push Nuget
      if: ${{ env.VERSION == 'TRUE' }}
      run: dotnet nuget push bin/artifacts/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_TOKEN }} --skip-duplicate